/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fuchao_ffmpegandroidplayer_GlVideoView */

#ifndef _Included_com_fuchao_ffmpegandroidplayer_GlVideoView
#define _Included_com_fuchao_ffmpegandroidplayer_GlVideoView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fuchao_ffmpegandroidplayer_GlVideoView
 * Method:    onNdkSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fuchao_ffmpegandroidplayer_GlVideoView_onNdkSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_fuchao_ffmpegandroidplayer_GlVideoView
 * Method:    onNdkSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_fuchao_ffmpegandroidplayer_GlVideoView_onNdkSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_fuchao_ffmpegandroidplayer_GlVideoView
 * Method:    onNdkGetFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fuchao_ffmpegandroidplayer_GlVideoView_onNdkGetFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_fuchao_ffmpegandroidplayer_GlVideoView
 * Method:    onNdkDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fuchao_ffmpegandroidplayer_GlVideoView_onNdkDrawFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_fuchao_ffmpegandroidplayer_GlVideoView
 * Method:    onNdkDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fuchao_ffmpegandroidplayer_GlVideoView_onNdkDestory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
